### ISSUE TITLE
Research Git Hooks

### ISSUE THREAD

**Issue by hasansultan92** [hasansultan92/ECE461Part2#1]
Look more into what Git Hooks are and potentially how we can use them with this repo

**Comment by jasonbleasdell** [comment]
add the .git hook folder 
git hooks for commit so we run the linter or something
git hooks for push so we can do something 

when this is finished pull request into dev directly from your fork git-hooks.

**Comment by jasonbleasdell** [comment]
https://www.atlassian.com/git/tutorials/git-hooks
https://stackoverflow.com/questions/12222186/are-git-hooks-pushed-to-the-remote-when-i-git-push
https://stackoverflow.com/questions/3462955/putting-git-hooks-into-a-repository
