### ISSUE TITLE
Add typscript linter and python linter on the github.com side

### ISSUE THREAD

**Issue by jasonbleasdell** [hasansultan92/ECE461Part2#15]
once you push to github it should run the linter automatically and later it will also run the test suite

**Comment by krobinson395** [comment]
Capability is present

**Comment by hasansultan92** [comment]
[3d30a8b](https://github.com/hasansultan92/ECE461Part2/commit/3d30a8bb04d10c66ae9fde451a70cd7785ea85c1)
