### ISSUE TITLE
Research on CI & CD

### ISSUE THREAD

**Issue by hasansultan92** [hasansultan92/ECE461Part2#2]
Look into what CI and CD are. Look into how we can potentially use them in the future.

**Comment by jasonbleasdell** [comment]
add the .git hook folder 
ci for running github actions automatically on a push
cd for automatically updating gcp from our main branch

**Comment by hasansultan92** [comment]
Added some basic CI functionality to codebase. Codebase runs a compilation/building check and environment setup on ubuntu. Will add CD options once we delve into GCP Suite a little bit more
