### ISSUE TITLE
Validation of user input

### ISSUE THREAD

**Issue by hasansultan92** [hasansultan92/ECE461Part2#23]
Should validate the input for the user either on the front end or on the back end

EDIT: below

Is the username going to be lowercase all the time?
How many characters can the password be?

**Comment by krobinson395** [comment]
Do we want/need to hash any user input or just ensure base functionality?

**Comment by hasansultan92** [comment]
Nope. This is more along the lines that we need to decide if the password needs to be a certain length for example or if the username has to be lowercase. Information like that would be useful

**Comment by hasansultan92** [comment]
Duplicate to #20
